/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.belili.view;

import com.belili.dao.UserDAO;
import com.belili.dao.impl.UserDAOImpl;
import com.belili.pojo.User;
import java.util.ArrayList;
import javax.swing.JTable;

/**
 *
 * @author belili
 */
public class View_dialog_listUser extends javax.swing.JDialog {

    /**
     * Creates new form View_dialog_listUser
     */
    public View_dialog_listUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //buildTable();
    }

//    private void buildTable() {
//
//        String titulos[] = {"Codigo", "Nombres", "Correo", "Telefono",};
//        String informacion[][] = getList();
//        table_moduloUser = new JTable(informacion, titulos) {
//            @Override
//            public boolean isCellEditable(int row, int column) {
//                return false;
//                //return super.isCellEditable(row, column);
//            }
//        };
//        jScrollPane1.setViewportView(table_moduloUser);
//    }
//
//    private String[][] getList() {
//
//        UserDAO daoList = new UserDAOImpl();
//        ArrayList<User> miLista = (ArrayList<User>) daoList.selectAll();
//        String matrizInfo[][] = new String[miLista.size()][8];
//
//        for (int i = 0; i < miLista.size(); i++) {
//            matrizInfo[i][0] = miLista.get(i).getCodeUser() + "";
//            matrizInfo[i][1] = miLista.get(i).getFullnameUser() + "";
//            matrizInfo[i][2] = miLista.get(i).getCorreoUser() + "";
//            matrizInfo[i][3] = miLista.get(i).getPhoneUser() + "";
//        }
//        return matrizInfo;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_updateDataList = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_moduloUser = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText(" ");
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jLabel3.setText("     ");
        getContentPane().add(jLabel3, java.awt.BorderLayout.LINE_START);

        jLabel4.setText("     ");
        getContentPane().add(jLabel4, java.awt.BorderLayout.LINE_END);

        jLabel5.setText(" ");
        getContentPane().add(jLabel5, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);
        jPanel1.add(jLabel6, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));
        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel8.setText("               ");
        jPanel5.add(jLabel8, java.awt.BorderLayout.LINE_START);

        jLabel9.setText("               ");
        jPanel5.add(jLabel9, java.awt.BorderLayout.LINE_END);

        btn_updateDataList.setText("Actualizar");
        btn_updateDataList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateDataListActionPerformed(evt);
            }
        });
        jPanel5.add(btn_updateDataList, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel7.setText(" ");
        jPanel3.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        table_moduloUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_moduloUser);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateDataListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateDataListActionPerformed
        //buildTable();
    }//GEN-LAST:event_btn_updateDataListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_dialog_listUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_dialog_listUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_dialog_listUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_dialog_listUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                View_dialog_listUser dialog = new View_dialog_listUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_updateDataList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable table_moduloUser;
    // End of variables declaration//GEN-END:variables
}
