package com.belili.pojo;
// Generated Aug 15, 2018 2:11:01 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer idCustomer;
     private User user;
     private String codeCustomer;
     private String nameCustomer;
     private String lastnameCustomer;
     private String dniCustomer;
     private String addressCustomer;
     private String correoCustomer;
     private String phone1Customer;
     private String phone2Customer;
     private boolean stateCustomer;
     private Date dateCustomer;

    public Customer() {
    }

	
    public Customer(User user, String codeCustomer, String nameCustomer, String lastnameCustomer, String dniCustomer, boolean stateCustomer) {
        this.user = user;
        this.codeCustomer = codeCustomer;
        this.nameCustomer = nameCustomer;
        this.lastnameCustomer = lastnameCustomer;
        this.dniCustomer = dniCustomer;
        this.stateCustomer = stateCustomer;
    }
    public Customer(User user, String codeCustomer, String nameCustomer, String lastnameCustomer, String dniCustomer, String addressCustomer, String correoCustomer, String phone1Customer, String phone2Customer, boolean stateCustomer, Date dateCustomer) {
       this.user = user;
       this.codeCustomer = codeCustomer;
       this.nameCustomer = nameCustomer;
       this.lastnameCustomer = lastnameCustomer;
       this.dniCustomer = dniCustomer;
       this.addressCustomer = addressCustomer;
       this.correoCustomer = correoCustomer;
       this.phone1Customer = phone1Customer;
       this.phone2Customer = phone2Customer;
       this.stateCustomer = stateCustomer;
       this.dateCustomer = dateCustomer;
    }
   
    public Integer getIdCustomer() {
        return this.idCustomer;
    }
    
    public void setIdCustomer(Integer idCustomer) {
        this.idCustomer = idCustomer;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCodeCustomer() {
        return this.codeCustomer;
    }
    
    public void setCodeCustomer(String codeCustomer) {
        this.codeCustomer = codeCustomer;
    }
    public String getNameCustomer() {
        return this.nameCustomer;
    }
    
    public void setNameCustomer(String nameCustomer) {
        this.nameCustomer = nameCustomer;
    }
    public String getLastnameCustomer() {
        return this.lastnameCustomer;
    }
    
    public void setLastnameCustomer(String lastnameCustomer) {
        this.lastnameCustomer = lastnameCustomer;
    }
    public String getDniCustomer() {
        return this.dniCustomer;
    }
    
    public void setDniCustomer(String dniCustomer) {
        this.dniCustomer = dniCustomer;
    }
    public String getAddressCustomer() {
        return this.addressCustomer;
    }
    
    public void setAddressCustomer(String addressCustomer) {
        this.addressCustomer = addressCustomer;
    }
    public String getCorreoCustomer() {
        return this.correoCustomer;
    }
    
    public void setCorreoCustomer(String correoCustomer) {
        this.correoCustomer = correoCustomer;
    }
    public String getPhone1Customer() {
        return this.phone1Customer;
    }
    
    public void setPhone1Customer(String phone1Customer) {
        this.phone1Customer = phone1Customer;
    }
    public String getPhone2Customer() {
        return this.phone2Customer;
    }
    
    public void setPhone2Customer(String phone2Customer) {
        this.phone2Customer = phone2Customer;
    }
    public boolean isStateCustomer() {
        return this.stateCustomer;
    }
    
    public void setStateCustomer(boolean stateCustomer) {
        this.stateCustomer = stateCustomer;
    }
    public Date getDateCustomer() {
        return this.dateCustomer;
    }
    
    public void setDateCustomer(Date dateCustomer) {
        this.dateCustomer = dateCustomer;
    }




}


