package com.belili.pojo;
// Generated Aug 15, 2018 2:11:01 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Provider generated by hbm2java
 */
public class Provider  implements java.io.Serializable {


     private Integer idProvider;
     private User user;
     private String codeProvider;
     private String businessProvider;
     private String rucProvider;
     private String addressProvider;
     private String contactProvider;
     private String correoProvider;
     private String phone1Provider;
     private String phone2Provider;
     private boolean stateProvider;
     private Date dateProvider;

    public Provider() {
    }

	
    public Provider(User user, String codeProvider, String businessProvider, String rucProvider, boolean stateProvider) {
        this.user = user;
        this.codeProvider = codeProvider;
        this.businessProvider = businessProvider;
        this.rucProvider = rucProvider;
        this.stateProvider = stateProvider;
    }
    public Provider(User user, String codeProvider, String businessProvider, String rucProvider, String addressProvider, String contactProvider, String correoProvider, String phone1Provider, String phone2Provider, boolean stateProvider, Date dateProvider) {
       this.user = user;
       this.codeProvider = codeProvider;
       this.businessProvider = businessProvider;
       this.rucProvider = rucProvider;
       this.addressProvider = addressProvider;
       this.contactProvider = contactProvider;
       this.correoProvider = correoProvider;
       this.phone1Provider = phone1Provider;
       this.phone2Provider = phone2Provider;
       this.stateProvider = stateProvider;
       this.dateProvider = dateProvider;
    }
   
    public Integer getIdProvider() {
        return this.idProvider;
    }
    
    public void setIdProvider(Integer idProvider) {
        this.idProvider = idProvider;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCodeProvider() {
        return this.codeProvider;
    }
    
    public void setCodeProvider(String codeProvider) {
        this.codeProvider = codeProvider;
    }
    public String getBusinessProvider() {
        return this.businessProvider;
    }
    
    public void setBusinessProvider(String businessProvider) {
        this.businessProvider = businessProvider;
    }
    public String getRucProvider() {
        return this.rucProvider;
    }
    
    public void setRucProvider(String rucProvider) {
        this.rucProvider = rucProvider;
    }
    public String getAddressProvider() {
        return this.addressProvider;
    }
    
    public void setAddressProvider(String addressProvider) {
        this.addressProvider = addressProvider;
    }
    public String getContactProvider() {
        return this.contactProvider;
    }
    
    public void setContactProvider(String contactProvider) {
        this.contactProvider = contactProvider;
    }
    public String getCorreoProvider() {
        return this.correoProvider;
    }
    
    public void setCorreoProvider(String correoProvider) {
        this.correoProvider = correoProvider;
    }
    public String getPhone1Provider() {
        return this.phone1Provider;
    }
    
    public void setPhone1Provider(String phone1Provider) {
        this.phone1Provider = phone1Provider;
    }
    public String getPhone2Provider() {
        return this.phone2Provider;
    }
    
    public void setPhone2Provider(String phone2Provider) {
        this.phone2Provider = phone2Provider;
    }
    public boolean isStateProvider() {
        return this.stateProvider;
    }
    
    public void setStateProvider(boolean stateProvider) {
        this.stateProvider = stateProvider;
    }
    public Date getDateProvider() {
        return this.dateProvider;
    }
    
    public void setDateProvider(Date dateProvider) {
        this.dateProvider = dateProvider;
    }




}


